DROP TABLE IF EXISTs GMTle1;
DROP TABLE IF EXISTs GMTle2_1;
DROP TABLE IF EXISTs GMTle2_2;
DROP TABLE IF EXISTs GMTle2_3_1;
DROP TABLE IF EXISTs GMTle2_3_2;
DROP TABLE IF EXISTs GMTle2_3_3;
DROP TABLE IF EXISTs GMTle2_3_4;
DROP TABLE IF EXISTs GMTle2_4_1;
DROP TABLE IF EXISTs GMTle2_4_2;
DROP TABLE IF EXISTs GMTle2_4_3;
DROP TABLE IF EXISTs GMTle2_4_4;
DROP TABLE IF EXISTs GMTle3_1;
DROP TABLE IF EXISTs GMTle3_2_1;
DROP TABLE IF EXISTs GMTle3_2_2;
DROP TABLE IF EXISTs GMTle3_3_1;
DROP TABLE IF EXISTs GMTle3_3_2;
DROP TABLE IF EXISTs GMTle3_3_3;
DROP TABLE IF EXISTs GMTle3_4_1;
DROP TABLE IF EXISTs GMTle3_4_2;
DROP TABLE IF EXISTs GMTle3_5;
DROP SEQUENCE IF EXISTS global_seq1;
DROP SEQUENCE IF EXISTS global_seq2;
DROP SEQUENCE IF EXISTS global_seq3;
DROP SEQUENCE IF EXISTS global_seq4;
DROP SEQUENCE IF EXISTS global_seq5;
DROP SEQUENCE IF EXISTS global_seq6;
DROP SEQUENCE IF EXISTS global_seq7;
DROP SEQUENCE IF EXISTS global_seq8;
DROP SEQUENCE IF EXISTS global_seq9;
DROP SEQUENCE IF EXISTS global_seq10;
DROP SEQUENCE IF EXISTS global_seq11;
DROP SEQUENCE IF EXISTS global_seq12;
DROP SEQUENCE IF EXISTS global_seq13;
DROP SEQUENCE IF EXISTS global_seq14;
DROP SEQUENCE IF EXISTS global_seq15;
DROP SEQUENCE IF EXISTS global_seq16;
DROP SEQUENCE IF EXISTS global_seq17;
DROP SEQUENCE IF EXISTS global_seq18;
DROP SEQUENCE IF EXISTS global_seq19;
DROP SEQUENCE IF EXISTS global_seq20;



CREATE SEQUENCE global_seq1 START WITH 1;
CREATE SEQUENCE global_seq2 START WITH 1;
CREATE SEQUENCE global_seq3 START WITH 1;
CREATE SEQUENCE global_seq4 START WITH 1;
CREATE SEQUENCE global_seq5 START WITH 1;
CREATE SEQUENCE global_seq6 START WITH 1;
CREATE SEQUENCE global_seq7 START WITH 1;
CREATE SEQUENCE global_seq8 START WITH 1;
CREATE SEQUENCE global_seq9 START WITH 1;
CREATE SEQUENCE global_seq10 START WITH 1;
CREATE SEQUENCE global_seq11 START WITH 1;
CREATE SEQUENCE global_seq12 START WITH 1;
CREATE SEQUENCE global_seq13 START WITH 1;
CREATE SEQUENCE global_seq14 START WITH 1;
CREATE SEQUENCE global_seq15 START WITH 1;
CREATE SEQUENCE global_seq16 START WITH 1;
CREATE SEQUENCE global_seq17 START WITH 1;
CREATE SEQUENCE global_seq18 START WITH 1;
CREATE SEQUENCE global_seq19 START WITH 1;
CREATE SEQUENCE global_seq20 START WITH 1;

CREATE TABLE GMTable1
(
    id   INTEGER PRIMARY KEY DEFAULT nextval('global_seq1'),
    text VARCHAR NOT NULL
);

CREATE TABLE GMTable2_1
(
    id   INTEGER PRIMARY KEY DEFAULT nextval('global_seq2'),
    text VARCHAR NOT NULL
);

CREATE TABLE GMTable2_2
(
    id   INTEGER PRIMARY KEY DEFAULT nextval('global_seq3'),
    text VARCHAR NOT NULL
);

CREATE TABLE GMTable2_3_1
(
    id   INTEGER PRIMARY KEY DEFAULT nextval('global_seq4'),
    text VARCHAR NOT NULL
);

CREATE TABLE GMTable2_3_2
(
    id   INTEGER PRIMARY KEY DEFAULT nextval('global_seq5'),
    text VARCHAR NOT NULL
);

CREATE TABLE GMTable2_3_3
(
    id   INTEGER PRIMARY KEY DEFAULT nextval('global_seq6'),
    text VARCHAR NOT NULL
);

CREATE TABLE GMTable2_3_4
(
    id   INTEGER PRIMARY KEY DEFAULT nextval('global_seq7'),
    text VARCHAR NOT NULL
);

CREATE TABLE GMTable2_4_1
(
    id   INTEGER PRIMARY KEY DEFAULT nextval('global_seq8'),
    text VARCHAR NOT NULL
);

CREATE TABLE GMTable2_4_2
(
    id   INTEGER PRIMARY KEY DEFAULT nextval('global_seq9'),
    text VARCHAR NOT NULL
);

CREATE TABLE GMTable2_4_3
(
    id   INTEGER PRIMARY KEY DEFAULT nextval('global_seq10'),
    text VARCHAR NOT NULL
);

CREATE TABLE GMTable2_4_4
(
    id   INTEGER PRIMARY KEY DEFAULT nextval('global_seq11'),
    text VARCHAR NOT NULL
);

CREATE TABLE GMTable3_1
(
    id   INTEGER PRIMARY KEY DEFAULT nextval('global_seq12'),
    text VARCHAR NOT NULL
);

CREATE TABLE GMTable3_2_1
(
    id   INTEGER PRIMARY KEY DEFAULT nextval('global_seq13'),
    text VARCHAR NOT NULL
);

CREATE TABLE GMTable3_2_2
(
    id   INTEGER PRIMARY KEY DEFAULT nextval('global_seq14'),
    text VARCHAR NOT NULL
);

CREATE TABLE GMTable3_3_1
(
    id   INTEGER PRIMARY KEY DEFAULT nextval('global_seq15'),
    text VARCHAR NOT NULL
);

CREATE TABLE GMTable3_3_2
(
    id   INTEGER PRIMARY KEY DEFAULT nextval('global_seq16'),
    text VARCHAR NOT NULL
);

CREATE TABLE GMTable3_3_3
(
    id   INTEGER PRIMARY KEY DEFAULT nextval('global_seq17'),
    text VARCHAR NOT NULL
);

CREATE TABLE GMTable3_4_1
(
    id   INTEGER PRIMARY KEY DEFAULT nextval('global_seq18'),
    text VARCHAR NOT NULL
);

CREATE TABLE GMTable3_4_2
(
    id   INTEGER PRIMARY KEY DEFAULT nextval('global_seq19'),
    text VARCHAR NOT NULL
);

CREATE TABLE GMTable3_5
(
    id   INTEGER PRIMARY KEY DEFAULT nextval('global_seq20'),
    text VARCHAR NOT NULL
);